<?php
/**
 *
 */
?>
<?php $_product = Mage::registry('current_product'); ?>
<?php $giftcardType = $_product->getGiftcardType() == 0 ?  'virtual' :  'physical'; ?>
<li class="fields">
    <div class="field">
        <label for="giftcard_sender_name_<?php echo $giftcardType; ?>"
               class="required"><?php echo Mage::helper('enterprise_giftcard')->__('Your Name'); ?></label>

        <div class="input-box">
            <input type="text" id="giftcard_sender_name_<?php echo $giftcardType; ?>" name="giftcard_sender_name" class="required-entry input-text"
                   value="<?php echo $this->getCustomerName(); ?>"/>
        </div>
    </div>
    <?php if ($giftcardType == 'virtual'): ?>
        <div class="field">
            <label for="giftcard_sender_email_<?php echo $giftcardType; ?>"
                   class="required"><?php echo Mage::helper('enterprise_giftcard')->__('Your Email'); ?></label>

            <div class="input-box">
                <input type="text" id="giftcard_sender_email_<?php echo $giftcardType; ?>" name="giftcard_sender_email"
                       class="validate-email required-entry input-text"
                       value="<?php echo $this->getCustomerEmail(); ?>"/>
            </div>
        </div>
    <?php endif; ?>
</li>
