<?php
/**
 * SeeWhy
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     SeeWhy
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
    /** @$this Mage_Core_Block_Template */
?>
<script type="text/javascript">
    var SeewhyCustomerCode = '<?php echo Mage::getStoreConfig('tgc_seewhy/js/customer_code'); ?>';
</script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl()?>js/seewhy/WebEvent.js"></script>
