<?php
/**
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Lectures
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>

<div id="free_lectures_information" class="grid-full">
    <div class="grid12-6"><?php echo $this->getChildHtml('free_lectures_description') ?></div>
    <div class="grid12-6"><?php echo $this->getChildHtml('free_lectures_form') ?></div>
</div>