<?php
/**
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Lectures
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>

<?php echo $this->getChildHtml('free_lectures_title') ?>
<?php echo $this->getChildHtml('free_lectures_description') ?>
<?php echo $this->getChildHtml('free_lectures_information') ?>
<?php echo $this->getChildHtml('free_lectures_video_audio_collections') ?>
<?php echo $this->getChildHtml('free_lectures_about_tgc_blocks') ?>