<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */

/* @var $core Mana_Core_Helper_Data */
$core = Mage::helper('mana_core');

/* @var $filterHelper Mana_Filters_Helper_Data */
$filterHelper = Mage::helper('mana_filters');

?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Narrow Results') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($core->isMageVersionEqualOrGreater('1.7') && $this->getLayer()->getState()->getFilters()) : ?>
        <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <?php $_filterGroups = Mage::helper('mana_filters')->renderHtml($this, 'groups'); ?>
            <?php foreach ($_filterGroups as $_filterGroup): ob_start(); ?>
                <?php $_filters = $_filterGroup->getFilters(); ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                     <?php if($_filter->getFilterOptions()->getCode() != "best_selling" && $_filter->getFilterOptions()->getCode() != 'new_release'): ?>
                        <dt class="<?php $filterHelper->renderHtml($this, 'name_css', array('filter' => $_filter)); ?>"
                            <?php $filterHelper->renderHtml($this, 'name_attributes', array('filter' => $_filter)); ?>
                        >
                            <?php $clearUrl = Mage::helper('manapro_filterclear')->getClearUrl($_filter)?>
                            <input type="checkbox" name="<?php echo $_filter->getFilterOptions()->getCode() ?>_checkbox" <?php echo !$clearUrl ? 'checked="checked" disabled="disabled" class="checked disabled"' : 'class="unchecked"' ?> id="<?php echo $_filter->getFilterOptions()->getCode() ?>_checkbox"
                                   onClick="setLocation('<?php echo $clearUrl ?>');" />
                            <label for="<?php echo $_filter->getFilterOptions()->getCode() ?>_checkbox">
                                <?php $filterHelper->renderHtml($this, 'name_before', array('filter' => $_filter)); ?>
                                <?php echo $this->__($_filter->getName()) ?>
                                <?php $filterHelper->renderHtml($this, 'name_after', array('filter' => $_filter)); ?>
                            </label>
                        </dt>
                        <dd class="<?php $filterHelper->renderHtml($this, 'value_css', array('filter' => $_filter)); ?>">
                            <?php echo $_filter->getHtml() ?>
                        </dd>
                    <?php endif; ?>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if($_filterGroupHtml = trim(ob_get_clean())) : ?>
                    <?php $_filterGroupName = $_filterGroup->getName() ? $this->__($_filterGroup->getName()) : $this->__('Shopping Options'); ?>

                    <div class="block-subtitle m-filter-group <?php $filterHelper->renderHtml($this, 'group_css', array('group' => $_filterGroup)); ?>"
                        <?php $filterHelper->renderHtml($this, 'group_attributes', array('group' => $_filterGroup)); ?>
                    >
                        <?php $filterHelper->renderHtml($this, 'group_before', array('group' => $_filterGroup)); ?>
                        <?php echo $_filterGroupName ?>
                        <?php $filterHelper->renderHtml($this, 'group_after', array('group' => $_filterGroup)); ?>
                    </div>

                    <dl class="narrow-by-list" id="narrow-by-list-<?php echo $_filterGroup->getId() ?>">
                        <dt class="for-price-ranges-mobile show-for-mobile">
                            <input type="checkbox" name="prices_checkbox" id="prices_checkbox" checked="checked" disabled="disabled">
                            <label for="prices_checkbox">All Price Ranges</label>
                        </dt>
                        <dd class="for-price-ranges-mobile show-for-mobile">
                            <!--For Descktop version here should be list of prices checkboxes like for other-->


                            <!-- This is block for price ranges for mobile devices -->
                            <div class="price-ranges-inputs-box">
                                <input type="text" placeholder="Select low"/>
                                <span>to</span>
                                <input type="text" placeholder="Select high"/>
                            </div>
                        </dd>
                        <?php echo $_filterGroupHtml ?>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list-<?php echo $_filterGroup->getId() ?>')</script>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
