<?php
/**
 * Cms additions
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Cms
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
/** @var $this Tgc_Cms_Block_HeroCarousel */
?>
<?php
$collection = $this->getCollection();
$processor  = Mage::helper('cms')->getPageTemplateProcessor();
?>
<?php if ($this->shouldShowWidget() && $collection && ($collection->getSize())): ?>
    <div id="home-hero-slider-tab">
        <?php $iterator = 0; ?>
        <?php foreach ($collection as $item): ?>
            <?php $iterator++; ?>
            <div id="pane-<?php echo $iterator; ?>">
                <div class="tab-desktop">
                    <?php echo $processor->filter($item->getDescription()); ?>
                </div>
                <div class="tab-mobile">
                    <?php echo $processor->filter($item->getMobileDescription()); ?>
                </div>
            </div>
        <?php endforeach; ?>
        <?php $iterator = 0; ?>
        <ul class="clearfix">
            <?php foreach ($collection as $item): ?>
                <?php $iterator++; ?>
                <li>
                    <a href="#pane-<?php echo $iterator; ?>">
                        <strong><?php echo $item->getTabTitle(); ?></strong><?php echo $item->getTabDescription(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <script type="text/javascript">
        //<![CDATA[

        jQuery(function($) {

            $.fn.swipeTabs = function(config) {

                config = config || {};

                return this.each(function() {

                    var slider;
                    slider = $(this).sliderTabs(config);

                    slider.swipe({
                        allowPageScroll: 'vertical',
                        threshold:  100,
                        swipeLeft: function(event, direction, distance, duration, fingerCount) {
                            slider.data('sliderTabs').next();
                        },
                        swipeRight: function() {
                            slider.data('sliderTabs').prev();
                        }
                    });

                });

            };

            if ( isTouchable !== true ) {
                $("#home-hero-slider-tab").sliderTabs({
                    tabHeight: 'auto',
                    position: "bottom",
                    tabArrowWidth: 0,
                    transition: 'fade',
                    transitionSpeed: 500,
                    mousewheel: false
                });

            } else {
                $("#home-hero-slider-tab").swipeTabs({
                    tabHeight: 'auto',
                    position: "bottom",
                    tabArrowWidth: 0,
                    indicators: true,
                    transitionSpeed: 500,
                    mousewheel: false
                });
            }
            var intervalForResize;

            <?php $tabWidth = (100 / count($collection)); ?>

            intervalForResize = setInterval(function() {
                if (typeof modExp == "object") {
                    changeVideoSize();
                    clearInterval(intervalForResize);
                    $(window).resize(function() {changeVideoSize()});
                }
            }, 500);

            function changeVideoSize() {
                modExp.setSize($('.ui-slider-tabs-content-container').width(), $('.ui-slider-tabs-content-container').height());
                $('#brightCove-player object').css({'width' : $('.ui-slider-tabs-content-container').width(), 'height': $('.ui-slider-tabs-content-container').height()});
            }
            $(document).ready(function() {
                $('#home-hero-slider-tab .ui-slider-tabs-list li').css({'width' : '<?php echo $tabWidth . '%'; ?>', 'max-width' : 'inherit'});
                $('#home-hero-slider-tab .ui-slider-tabs-list li a').css({'min-height': '82px', 'height' : $('#home-hero-slider-tab .ui-slider-tabs-list').height()});
                $('#home-hero-slider-tab .ui-slider-tabs-list li a').on(customClickEvent, function (e) {
                    e.preventDefault();
                });
            });


        });
        //]]>
    </script>
<?php endif; ?>
