<?php
/**
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Wishlist
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
$item = $this->getItem();
?>
<div class="grid12-3 format-col">
    <?php echo $this->getItemOptionsHtml($item); ?>
    &nbsp;
    <script type="text/javascript">
        document.observe('dom:loaded', function () {
            addWItemToCart = function (itemId) {
                var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
                url = url.gsub('%item%', itemId);
                var form = $('wishlist-view-form');
                if (form) {
                    var separator;
                    var input = form['qty[' + itemId + ']'];
                    if (input) {
                        separator = (url.indexOf('?') >= 0) ? '&' : '?';
                        url += separator + input.name + '=' + encodeURIComponent(input.value);
                    }
                    var optionsInputs = form.select('input[name^="item_options[' + itemId + ']"]', 'select[name^="item_options[' + itemId + ']"]');
                    for (var i = 0, len = optionsInputs.length; i < len; i++) {
                        separator = (url.indexOf('?') >= 0) ? '&' : '?';
                        url += separator + optionsInputs[i].name + '=' + encodeURIComponent(optionsInputs[i].value);
                    }
                }
                setLocation(url);
            };
        });
    </script>
</div>
