<hr />
<div id="freelecture_unsubscribe">
    Our Privacy Policy<br />

    <p class="disclaimer">We will not sell or rent your name, address, e-mail address, or purchase history to any other person or company. Period. That
    has been our policy since we opened in 1990.</p>

    <p>Here&#39s what we do with your e-mail address:</p>


        <ul>
            <li><b>Send you order confirmations and course starter materials.</b> When you place an order, you&#39ll receive an order confirmation within moments. You&#39ll also receive
            the professor&#39s summary of the course, links to websites recommended by the professor to supplement your learning experience, and the recommended readings for the
            course with a link so you may order the readings if you choose.</li>
            <li><b>Send you free articles.</b> We search widely for articles of interest on the subjects covered by our courses. When we find one that is especially interesting or compelling,
                we&#39ll send it to you if we can arrange with the publisher to do so.</li>
            <li><b>Collect your feedback on courses and professors.</b> We work hard to stay in touch with you. Through e-mail surveys, you vote for the courses you want us to make, rate
            the quality of our courses, tell us what improvements to make to our courses and services, and tell us which professors we should choose to make The Great Courses.  The
            professors who teach The Great Courses were chosen based on the votes of more than 15,000 customers who have evaluated audition lectures.</li>
            <li><b>Notify you of special offers.</b> Each catalog and newsletter includes courses that are on sale. We also notify our customers via e-mail when courses are on sale.
            We also make buying simple via e-mail. If you see courses that interest you, simply click on the links to our website, where you can find out more.</li>
        </ul>
</div>