<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/validate-zip-ca.js') ?>"></script>
<label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?></label>
<div class="input-box">
<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>"
       name="billing[postcode]" id="billing:postcode"
       value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"/>
</div>
<script type="text/javascript">
//<!--
    document.observe('dom:loaded', function () {
        $('billing:country_id').on('change', function (event) {
            if ('US' == event.element().getValue()) {
                $('billing:postcode').addClassName('validate-zip');
                $('billing:postcode').removeClassName('validate-ca');
                $('billing:postcode').removeClassName('validate-zip-international');
            } else if ('CA' == event.element().getValue()) {
                $('billing:postcode').removeClassName('validate-zip');
                $('billing:postcode').removeClassName('validate-international');
                $('billing:postcode').addClassName('validate-zip-ca');
            } else {
                $('billing:postcode').removeClassName('validate-zip');
                $('billing:postcode').removeClassName('validate-ca');
                $('billing:postcode').addClassName('validate-zip-international');
            }
        });
    });
//-->
</script>
