<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl class="buffet-select-wrapper">
    <?php foreach($_attributes as $_attribute): ?>
        <?php /* ?><dt><label class="required"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt><?php */ ?>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            <div class="input-box">
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="<?php echo str_replace(array(1,2,3,4,5,6,7,8,9,0), array('a','b','c','d','e','f','g','h','i','j'), $_product->getId()); ?>attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                  </select>
              </div>
        </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        var productConfig = <?php echo $this->getJsonConfig() ?>;
        productConfig.containerId = 'add_to_cart_form_<?php echo $_product->getId(); ?>';
        productConfig.disablePriceReload = true;
        productConfig.chooseText = '<?php echo $this->hasChooseText() ? $this->getChooseText() : $this->__('Select Format'); ?>';
        var spConfig_<?php echo $_product->getId(); ?> = new Product.Config(productConfig);

        $('add_to_cart_form_<?php echo $_product->getId(); ?>').getElements().each(function(el) {
            if(el.type == 'select-one') {
                if(el.options && (el.options.length > 1)) {
                    el.options[0].selected = true;
                    spConfig_<?php echo $_product->getId(); ?>.reloadOptionLabels(el);
                }
            }
        });
    </script>
<?php endif; ?>
