<?php
$currentFormName = Tgc_Catalog_Helper_Freemarketinglecture::FORM_FORGOTPASSWORD;
$shouldDisplayForm = $helperFreelectures->getFreelectureFormToDisplay() != $currentFormName ? ' style="display:none"' : ''
?>

<form method="post" id="free-lectures-form-validate-forgotpassword"
      action="<?php echo Mage::getUrl('customer/account/freelectureForgotpassword') ?>" <?php echo $shouldDisplayForm ?>>
    <h2>Password Assistance</h2>
    <p>Please enter your e-mail address associated with your Great Courses account. We will send
        you an email so you can reset your password. If you have problems, please <a href="<?php echo Mage::getBaseUrl() . 'contact-us' ?>">Contact Us</a></p>
    <div>
        <label>Email Address</label><input type="text" name="freelectures-forgotpassword"
                                           class="input-text required-entry freelecture-email-valid"/>
        <div class="action">
            <a id="freelecture-backtoreg" rel="nofollow" href="#"><?php echo $this->__('Back to free lectures registration.'); ?></a>
            <input type="hidden" id="current_freelectures_form_forogotpassword" name="freelectures[current_freelectures_form]" value="<?php echo $currentFormName ?>" />
            <input id="submitbutton-forgotpassword" type="submit" value="Submit" class="button"/><br /><br />
        </div>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[

    var freeLecturesForgotPassword = new VarienForm('free-lectures-form-validate-forgotpassword', true);

    //]]>
</script>