<?php
/**
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Wishlist
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
$_item = $this->getItem();
$_attributes = $this->getAllowAttributes();
?>
<?php if (count($_attributes)): ?>
<div id="configurable_options_<?php echo $_item->getId(); ?>">
    <?php foreach ($_attributes as $_attribute): ?>
    <select id="<?php echo str_replace(array(1,2,3,4,5,6,7,8,9,0), array('a','b','c','d','e','f','g','h','i','j'), $_item->getId()); ?>attribute<?php echo $_attribute->getAttributeId() ?>"
            name="item_options[<?php echo $_item->getId(); ?>][super_attribute][<?php echo $_attribute->getAttributeId() ?>]"
            class="format super-attribute-select">
        </select>
    <?php endforeach; ?>
    <script type="text/javascript">
        document.observe('dom:loaded', function () {
            var priceRangeContainer = $('configurable-price-to-' + '<?php echo $_item->getProduct()->getId() . '_' . $_item->getId(); ?>');
            var priceContainer = $('product-price-' + '<?php echo $_item->getProduct()->getId() . '_' . $_item->getId(); ?>');
            if (priceRangeContainer && priceContainer) {
                priceRangeContainer.up('.price-box,.price-boxsale').show();
                priceContainer.up('.price-box').hide();
            }
            var spConfig = <?php echo $this->getJsonConfig() ?>;
            var priceConfig = <?php echo $this->getPriceJsonConfig() ?>;
            priceConfig.productId = '<?php echo $_item->getProduct()->getId() . '_' . $_item->getId(); ?>';
            spConfig.optionsPrice = new Product.OptionsPrice(priceConfig);
            spConfig = new Product.Config(spConfig);
        });
    </script>
</div>
<?php endif; ?>
