<?php
/**
 * DataMart integration
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     DataMart
 * @copyright   Copyright (c) 2013 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
/** $this Tgc_Datamart_Block_Product_Widget_PdpRecommended */
$imgWidth = 45;
$imgHeight = 65;
$helpImg = $this->helper('infortis/image');
?>
<?php if (($_products = $this->getProductCollection()) && count($_products) > 0): ?>
<div class="widget widget-upsell-products">
    <div class="widget-title">
        <h2><?php echo $this->__('You May Also Like:') ?></h2>
    </div>
    <div class="widget-products">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-you-may-also-like">
        <?php foreach ($_products->getItems() as $_product): ?>
            <?php
                $skipSaleableCheck = Mage::helper('catalog/product')->getSkipSaleableCheck();
                $allProducts       = $_product->getTypeInstance(true)
                    ->getUsedProducts(null, $_product);
                $instance = $_product->getTypeInstance(true)->getConfigurableAttributes($_product)->getFirstItem();
                $attributeId = $instance->getAttributeId();
            ?>
            <li class="item">
                <form id="add-to-cart-product-recommended" action="<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>" method="post">
                    <div class="ymal-left-side">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                            <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'thumbnail'); ?>" width="45" height="65" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                        </a>
                            <h3 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true); ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a>
                            </h3>
                            <div class="product-info">
                                <?php $professors = Mage::getResourceModel('profs/professor_collection')
                                    ->addProductToFilter($_product)
                                    ->addAlmaMaterList()
                                    ->addSchoolList() ?>
                                <?php if (count($professors) > 1): ?>
                                    <div class="professor">
                                        <div class="professor-name">
                                            <?php echo $this->__('Taught By Multiple Professors'); ?>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <?php foreach ($professors as $professor) : ?>
                                        <div class="professor">
                                            <div class="professor-name"><?php echo $this->escapeHtml("{$professor->getQual()} {$professor->getFirstName()} {$professor->getLastName()}") ?></div>
                                            | <?php echo $this->escapeHtml($professor->getSchoolList() . ', ' . $professor->getAlmaMaterList()) ?>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <div class="rating-price">
                                <?php if (Mage::helper('tgc_bv')->isBvEnabled()): ?>
                                    <?php echo Mage::helper('bazaarvoice')->getInlineRatingForProduct($_product); ?>
                                <?php endif; ?>
                                <div class="price-box">
                                    <?php $i = true; foreach ($allProducts as $child) { ?>
                                    <div class="price-child price-child-<?php echo $child->getId(); if ($i) { echo " show"; $i = false; } ?>" data-id="<?php echo $child->getCourseId(); ?>" data-sku="<?php echo $child->getSku(); ?>">
                                            <?php if ($child->getPrice() > $child->getFinalPrice()) { ?>
                                            <div class="price-with-special"><?php echo Mage::app()->getStore()->formatPrice($child->getPrice()) ?>
                                            </div>
                                            <div class="special-price">NOW <?php echo Mage::app()->getStore()->formatPrice($child->getFinalPrice()) ?>					</div>
                                            <?php } else { ?>
                                                <div class="price"><?php echo Mage::app()->getStore()->formatPrice($child->getFinalPrice()) ?></div>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                                <div class="information-needed" style="display: none">
                                    <input name="course_id" type="text" value="<?php echo $_product->getCourseId() ?>"/>
                                    <input name="product" type="text" value="<?php echo $_product->getId() ?>"/>
                                    <input name="product_sku" type="text" value="<?php echo $_product->getSku() ?>"/>
                                </div>

                                <div class="media-format-select">
                                    <select id="recommended-options-select" name="super_attribute[<?php echo $attributeId ?>]">
                                        <?php  $i = true; foreach ($allProducts as $child) { ?>
                                            <option id="<?php echo $child->getId() ?>" <?php if ($i) { echo "selected=selected"; $i = false; } ?> value="<?php echo $child->getMediaFormat() ?>"><?php echo $child->getAttributeText('media_format') ?></option>
                                        <?php } ?>
                                    </select>
                                </div>

                                <div class="add-to-cart-recommended">
                                    <input id="add-to-cart-recommended" type="checkbox" name="add_to_cart">
                                    <label for="add-to-cart-recommended">Add to Cart</label>
                                </div>

                        </div>
                    </div>

                    <div class="buttons-to-submit">
                        <button id="checkout-now" class="button checkout-now btn-checkout"><span><span><?php echo $this->__('CHECK OUT NOW') ?></span></span></button>
                        <div>
                            <span><?php echo $this->__('Or') ?></span> <a href="<?php echo Mage::getBaseUrl() . 'courses'; ?>" class="continue-shopping-recommended"><?php echo $this->__('Continue Shopping') ?></a>
                        </div>
                    </div>
                </form>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    var recommendedToCart = false;
    var recommendedAddToCartForm = new VarienForm('add-to-cart-product-recommended');

    jQuery('#recommended-options-select').on('change', function(){
        changePriceByAttribute();
    });

    function changePriceByAttribute() {
        jQuery('.price-child.show').each(function(e) {
            jQuery(this).removeClass('show');
        });
        jQuery('.price-child-' + jQuery('#recommended-options-select').find(":selected").attr('id')).addClass('show');
    }

    jQuery('#checkout-now').on(customClickEvent, function(event){
        event.preventDefault();
        addRecommendedAndGoTo('<?php echo $this->getUrl('checkout/cart', array('_secure'=>true)) ?>');
    });

    function addRecommendedAndGoTo(url) {
        if (recommendedToCart) {
            if (recommendedAddToCartForm.validator.validate()) {
                var id = jQuery('#add-to-cart-product-recommended').find('div.price-box div.price-child.show').attr('data-id');
                var sku = jQuery('#add-to-cart-product-recommended').find('div.price-box div.price-child.show').attr('data-sku');
                var price = jQuery('#add-to-cart-product-recommended').find('div.price-box div.price-child.show div.price span.price').text();
                price = price.trim().replace('$', '').replace('£', '');
                var form = recommendedAddToCartForm.form;
                try {
                    new Ajax.Request(form.action,
                        {
                            method: 'post',
                            parameters: $(form.id).serialize(true),
                            onSuccess: function (transport) {
                                updateTopLinks();
                                if(typeof window.utag_data == "object" && typeof window.utag == "object" && typeof window.utag.link == "function"){
                                    if (window.tgc_tealiumObj.addToCartYmalEvent(id, sku, price)) {
                                        setLocation(url);
                                    } else {
                                        setLocation(url);
                                    }
                                }
                            },
                            onLoading: function (request, json) {
                                $(document.body).scrollTo();
                            },
                            onFailure: function () {
                                updateTopLinks();
                            }
                        });
                } catch (e) {
                }
            }
        } else {
            setLocation(url);
        }
    }

    jQuery('#add-to-cart-recommended').on('change', function() {
        setRecommended();
    });

    function setRecommended() {
        if (recommendedToCart) {
            recommendedToCart = false;
        } else {
            recommendedToCart = true;
        }
    }

    jQuery('body').on(customClickEvent, '#messages_product_view, #messages_product_view .close-button, .continue-shopping-recommended', function() {
        if (recommendedToCart) {
            if (recommendedAddToCartForm.validator.validate()) {
                var id = jQuery('#add-to-cart-product-recommended').find('div.price-box div.price-child.show').attr('data-id');
                var sku = jQuery('#add-to-cart-product-recommended').find('div.price-box div.price-child.show').attr('data-sku');
                var price = jQuery('#add-to-cart-product-recommended').find('div.price-box div.price-child.show div.price span.price').text();
                price = price.trim().replace('$', '').replace('£', '');
                var form = recommendedAddToCartForm.form;
                try {
                    new Ajax.Request(form.action,
                        {
                            method: 'post',
                            parameters: $(form.id).serialize(true),
                            onSuccess: function (transport) {
                                updateTopLinks();
                                if(typeof window.utag_data == "object" && typeof window.utag == "object" && typeof window.utag.link == "function"){
                                    window.tgc_tealiumObj.addToCartYmalEvent(id, sku, price)
                                }
                            },
                            onLoading: function (request, json) {
                                $(document.body).scrollTo();
                            },
                            onFailure: function () {
                                updateTopLinks();
                            }
                        });
                } catch (e) {
                }
            }
        }
        jQuery('.pdp-drawer-block').animate({
            height: "0",
            opacity: 0
          }, 500);
    });

    jQuery(function($) {
        $('#recommended-options-select').coreUISelect();
    });

</script>
<?php endif; ?>
