<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * bool Add openers if menu is used as accordion
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php
	$helper = Mage::helper('ultramegamenu');
	if ($helper->getCfg('general/enable')):
?>

<?php
	$mode = $helper->getCfg('general/mode');
	// -1	= mobile menu only
	// 0	= both
	// 1	= drop-down menu only

	$categories = $helper->getCfg('general/categories');
	$linksHtml = $this->getChildHtml('block_nav_links');
    $moreSectionHtml = $this->getChildHtml('more_in_megamenu');
	$menuCss = array();
	if ($helper->getCfg('mainmenu/classic_menu'))
	{
		$menuCss[] = 'classic';
	}
	if ($helper->getCfg('mainmenu/wide_menu'))
	{
		$menuCss[] = 'wide';
	}
?>

<?php //Drop-down main menu ?>
<?php if ($mode >= 0): //Mode: drop-down or both ?>
        <div id="nav-home" class="level0 level-top">
            <span class="all-courses-js text-header-nav-medium menu-container nav-arrow-down">
                <a href="/courses" class="nav-text-link"><?php echo $this->__('courses');?></a>
            </span>
    <div id="nav" class="<?php if($menuCss) echo " " . implode(" ", $menuCss); ?>">
<!--        <a class="close-main-menu" href="#">x</a>-->

        <h4>Categories</h4>
        <ul class="megamenu-list clearfix">

            <?php //Categories ?>
            <?php if ($categories): ?>
                <?php echo $this->renderCategoriesMenuHtml(FALSE, 0, 'level-top'); ?>
            <?php endif; ?>

            <?php //Static block as a drop-down box ?>
        </ul>

        <!--Here will be MORE SECTION-->
        <?php echo $this->getChildHtml('more_in_megamenu');?>

        <?php //Custom links ?>
        <?php echo $linksHtml; ?>


    </div>
</div>

<?php endif; ?>

<?php //Activate mobile menu ?>
<?php if ($mode <= 0): //Mode: mobile or both ?>

	<script type="text/javascript">
	//<![CDATA[
		jQuery(function($) {

			<?php if ($mode == 0): //Mode: both ?>

				<?php $threshold = intval($helper->getCfg('mobilemenu/threshold')); ?>
				var activateMobileMenu = function()
				{
					if ($(window).width() < <?php echo $threshold; ?>)
					{
						$('#mobnav').show();
						$('.vertnav-top').addClass('mobile');
						$('#nav').addClass('mobile');
					}
					else
					{
						$('#nav').removeClass('mobile');
						$('.vertnav-top').removeClass('mobile');
						$('#mobnav').hide();
					}
				}
				activateMobileMenu();
				$(document).on("themeResize", activateMobileMenu);

			<?php else: //Mode: mobile ?>

				$('#mobnav').show();
				$('.vertnav-top').addClass('mobile');

			<?php endif; ?>

			<?php //Toggle mobile menu ?>
			$('#mobnav-trigger').toggle(function() {
				$(this).addClass('active');
				$('.vertnav-top').addClass('show');
			}, function() {
				$(this).removeClass('active');
				$('.vertnav-top').removeClass('show');
			});

		});
	//]]>
	</script>

<?php endif; ?>

<?php //Wide menu style. Mode: mobile or both ?>
<?php if (($mode >= 0) && $helper->getCfg('mainmenu/wide_menu')): ?>

	<script type="text/javascript">
	//<![CDATA[
		jQuery(function($) {
			$("#nav > li").hover(function() {
				var el = $(this).find(".level0-wrapper");
				el.hide();
				el.css("left", "0");
				el.stop(true, true).delay(150).fadeIn(300, "easeOutCubic");
			}, function() {
				$(this).find(".level0-wrapper").stop(true, true).delay(300).fadeOut(300, "easeInCubic");
			});
		});
	//]]>
	</script>

<?php endif; ?>

<?php endif; //end: if 'general/enable' ?>