<?php /* @var $this Infortis_UltraMegamenu_Block_Navigation */ ?>
<?php
/**
 * Sidebar menu
 */
?>
<?php
	$helper = Mage::helper('ultramegamenu');
	$visibilityClass = $helper->getCfg('sidemenu/hide_on_mobile') ? 'hide-below-768' : '';
?>
<?php if ($helper->getCfg('sidemenu/enable')): ?>
<div class="block block-vertnav<?php echo " $visibilityClass"; ?>">
	<div class="block-content">
		<ul class="accordion accordion-style1 vertnav vertnav-side clearer">
			<?php echo $this->renderCategoriesMenuHtml(TRUE, 0, 'level-top'); ?>
		</ul>
    </div>
</div>
<?php endif; ?>
