<link rel="stylesheet" href="<?php echo Mage::getBaseUrl('js').'events'. DS .'lightbox'. DS;?>css/lightbox.css" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'events'. DS .'lightbox'. DS .'js'. DS;?>lightbox.js"></script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "dc20c671-3d88-4c19-b79b-7a996fe07904"});</script>
<?php if (Mage::helper('events')->isEnableMapShow()) :?>
<script type="text/javascript">
jQuery(document).ready(function () {
	var cursorX;
	var cursorY;
	if (window.Event) {
		document.captureEvents(Event.MOUSEMOVE);
	}
	document.onmousemove = getCursorXY;
	jQuery(".mapThis").each(function() {
		var dPlace = jQuery(this).attr("place");
		var dZoom = jQuery(this).attr("zoom");
		var dText = jQuery(this).html();
		jQuery(this).html('<a onmouseover="mapThis.show(this);" style="text-decoration:none; border-bottom:1px dotted #999" href="http://maps.google.com/maps?q=' + dPlace + '&z=' + dZoom + '">' + dText + '</a>');
	});
});
	var mapThis=function(){
		var tt;
		var errorBox;
		return{
			show:function(v){
				if (tt == null) {
					var pNode = v.parentNode;
					pPlace = jQuery(pNode).attr("place");
					pZoom = parseInt(jQuery(pNode).attr("zoom"));
					pText = jQuery(v).html();
					tt = document.createElement('div');
					jQuery(tt).html('<a href="http://maps.google.com/maps?q=' + pPlace + '&z=11" target="new"><img border=0 src="http://maps.google.com/maps/api/staticmap?center=' + pPlace + '&zoom=' + pZoom + '&size=300x300&sensor=false&format=png&markers=color:blue|' + pPlace + '"></a>');
					tt.addEventListener('mouseover', function() { mapHover = 1; }, true);
					tt.addEventListener('mouseout', function() { mapHover = 0; }, true);
					tt.addEventListener('mouseout', mapThis.hide, true);
					document.body.appendChild(tt);
				}
				fromleft = cursorX;
				fromtop = cursorY;
				fromleft = fromleft - 25;
				fromtop = fromtop - 25;
				tt.style.cssText = "position:absolute; left:" + fromleft + "px; top:" + fromtop + "px; z-index:999; display:block; padding:1px; margin-left:5px; background-color:#333; width:302px; -moz-box-shadow:0 1px 10px rgba(0, 0, 0, 0.5);";
				tt.style.display = 'block';
			},
			hide:function(){
				tt.style.display = 'none';
				tt = null;
			}
	};
}();
function getCursorXY(e) {
	cursorX = (window.Event) ? e.pageX : event.clientX + (document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft);
	cursorY = (window.Event) ? e.pageY : event.clientY + (document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop);
} 
</script>
<?php endif;?>
<?php 
	$item 			= $this->getEvents();
	$isExpiredEvent	= Mage::helper('events')->isExpiredEvent($item['event_id']);
	$product 		= $this->getEventProduct(); 
	$catalog 		= Mage::getModel('catalog/product');
	$_product 		= $catalog->load($product); //echo '<pre>';print_r($_product);exit;
	$typeProduct 	= $_product['type_id'];
	$stockLevel 	= (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); //echo $stockLevel;exit;
	/* @param int $stockLevel @return int stock level in number */
	$prefix 		= $this->getRequest()->getParam('pfx');
	$medPath 		= Mage::getBaseUrl('media').'events'. DS .'mediums';
	$path 			=  Mage::getBaseUrl('media');
	$img 			= $path. DS .$item['event_image'];
	
	$expiredStatus 	= Mage::helper('events')->getNotificationType(1);
	$stockOut		= Mage::helper('events')->getNotificationType(0);
	/* store configuration for notification types */
	$prevUrlLink	= '';
	
	if (!Mage::helper('events')->isEnableBreadcrumbs())
	{
		$prevUrl = $_SERVER ['HTTP_REFERER'];
		$prevUrlLink = "<a href='".$prevUrl."'>".$this->__('Back')." << </a>";
	}
 ?>
<?php if ($item): ?>
<div class="eventviewDIV">
	<h3><?php echo $item['event_title']; ?></h3>
    <h3><?php echo $item['location_name']; ?></h3>
    <h3><?php echo $item['event_type_name']; ?></h3>
</div>
<p style="font-size: small;color: #777"><strong><?=$this->__('From')?> :</strong> <?php echo date('M jS, Y - h:i a', strtotime($item['event_start_date'])); ?> <strong><?=$this->__('To')?> :</strong> <?php echo date('M jS, Y - h:i a', strtotime($item['event_end_date'])); ?> <strong> <?=$this->__('Venue')?> : </strong> <span class="mapThis" place="<?php echo stripslashes($item['contact_address']) ?>" zoom="10"><?php echo $item['event_venu'] ?></span></p>
<?php if (!$isExpiredEvent): ?>
<!-- Ticket section begins -->
	<?php if ($product > 0 AND $stockLevel > 0 OR $typeProduct == 'configurable'): ?>
		 <div style="width:100%; text-align: right;">
			<strong><?=$this->__('Buy Tickets')?> : </strong>
				<?php
					$model = Mage::getModel('catalog/product')->load($product);
					$name = $model->getName();        
				?>
			<a href="<?php echo Mage::getUrl('checkout/cart/add', array('product' => $product)) ?>"><?php echo $name; ?></a>&nbsp;
		   </div>
	<?php elseif ($product > 0 AND $stockLevel == 0): ?>
		   <div style="width:100%; text-align: right;">
			<strong><?=$this->__('Buy Tickets')?> : </strong>
				<p><?php echo $stockOut; ?></p>
		   </div>
   <?php endif; ?>
   <!-- Ticket section ends -->
<?php else: ?>
	<div style="width:100%; text-align: right;">
		<strong><?php echo $expiredStatus; ?></strong>
	</div>
<?php endif; ?>   
   <br style="clear: both;"/>
   <!-- Main Image begins -->
   <?php if ($img) :?>
		<div class="event-contents">
			<span style="float: left">
				<img src="<?php echo $img; ?>" alt="<?php echo $item['event_title']?>"
					 width = "465px"
					 style="border: 1px solid #d5d5d5;padding:3px;margin-right: 10px;" />
			</span>
			<br style="clear: both;"/>
			<span>
				<p><?php echo $item['event_content']; ?></p>
			</span>
			<p style="clear: both"></p>
		</div>
	<?php endif; ?>
	<!-- Main Image ends -->
<p style="font-size: small;color: #777">
<?php if($item["contact_name"] != ''){ ?><strong><?=$this->__('Contact Person')?> :</strong> <?php echo $item['contact_name']; } ?>
<?php if($item["contact_phone"] != ''){ ?><strong> <?=$this->__('Phone')?> : </strong> <?php echo $item['contact_phone']; }?>
<?php if($item["contact_fax"] != ''){ ?><strong> <?=$this->__('Fax')?> : </strong> <?php echo $item['contact_fax']; }?>
<?php if($item["contact_email"] != ''){ ?><br /><strong><?=$this->__('Email')?> :</strong> <?php echo $item['contact_email']; } ?>
<?php if($item["contact_address"] != ''){ ?><strong> <?=$this->__('Address')?> : </strong> <?php echo $item['contact_address']; }?>
</p>
<!-- Gallery section begins -->
<?php
	$gallery = $this->getEventGallery();
	$path = Mage::getBaseUrl('media').'events';
	if (!empty($gallery)): ?>
	
	<style type="text/css">
	.carousel { position:relative; clear:both; left:0px; margin-top:10px; 
        border:2px solid #555555; background-color:#333333;
    }
    .carousel .navButton {
        cursor:pointer; display:block; text-indent:-9999px; background-repeat:none; z-index:10;
    }
    .carousel .container { position:absolute; overflow:hidden; }
    .carousel .items { position:absolute; }
    .carousel .item { position:relative;
        cursor:pointer;
	    filter:progid:DXImageTransform.Microsoft.Alpha(opacity=70);
        -moz-opacity:0.7;
        opacity:0.7;
        list-style-type:none; margin:0px; 
    }
    .carousel .item.hover, .carousel .item.selected { 
	    filter:progid:DXImageTransform.Microsoft.Alpha(opacity=100);
        -moz-opacity:1.0;
        opacity:1.0;    
    }
		 /* Horizontal Carousel */
    #Carousel2 { height:88px; width:465px; }
    #Carousel2 .container { left:26px; top:12px; width:416px; height:100px; }        
    #Carousel2 .items { top:0; left:2px; width:1000px;}
    #Carousel2 .item { height:70px;  width:70px; float:left; clear:right; }
    #Carousel2 .item .icon img { position:relative; left:0px; width:65px !important; height:65px; cursor:pointer;}
    #Carousel2 .navButton { position:absolute; bottom:-33px; width:24px; height:87px; }
    #Carousel2 .navButton.previous {  left:0px; background-image:url('<?php echo Mage::getBaseUrl('js').'events'. DS;?>images/interface/button.left.png'); background-repeat:no-repeat;}
    #Carousel2 .navButton.next { right:0px; background-image:url('<?php echo Mage::getBaseUrl('js').'events'. DS;?>images/interface/button.right.png'); background-repeat:no-repeat;}
    /* Hide data items from selector */
    #Carousel2 .item .key { display:none;}
    #Carousel2 .item .picture { display:none;}
	</style>
	    <div id="Carousel2" class="carousel">
                <div class="button navButton previous" style="display:none;"><?=$this->__('Back')?></div>
                <div class="button navButton next" style="display:none;"><?=$this->__('More')?></div>
                <div class="container">
                    <div class="items">
					<?php foreach ($gallery as $g): ?>
                        <div class="item">
                            <div class="key caption"><?=$this->__('Top')?></div>
                            <div class="icon">
                               <a class="noclass" href="<?php echo $path. DS .$g['image_file']; ?>" rel="lightbox[gallery]"><img alt="<?php echo $g['image_name']; ?>" src="<?php echo $path. DS .$g['image_file']; ?>"  width = "150px" height ="90px"/></a>
                            </div>
                            <div class="picture">
                               <a class="noclass" href="<?php echo $path. DS .$g['image_file']; ?>" rel=""><img alt="<?php echo $g['image_name']; ?>" src="<?php echo $path. DS .$g['image_file']; ?>"  width = "150px" height ="90px"/></a>
                            </div>
                        </div>            
                     <?php endforeach; ?>
                    </div>
                </div>
            </div>
    <script language="javascript" type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'events'. DS;?>clientscript/os.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'events'. DS;?>clientscript/model/carousel.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'events'. DS;?>clientscript/behavior/application.js"></script>
	<?php endif; ?>
	<!-- Gallery section ends -->
	<!-- Video section begins -->
	<?php if($item['event_video'] != ''):
			$videoId = '';
			$explode = explode('=', $item['event_video']);
			$videoId = $explode[1];
	?>
			<p style="clear: both"></p>
			<h3><?=$this->__('Event Video')?></h3>
			<iframe class="youtube-player" type="text/html" width="458" height="385" src="http://www.youtube.com/embed/<?php echo stripslashes($videoId); ?>" frameborder="0">
			</iframe>
	<?php endif;?>
	<!-- Video section ends -->
	<p style="clear: both;"></p>
	<!-- Social section -->

	<div class = "event_social_wdgt">
		<span class='st_fblike_hcount'></span><span class='st_twitter_hcount'></span><span class='st_plusone_hcount'></span><span class='st_email_hcount'></span><span class='st_sharethis_hcount'></span>
	</div>
	<p style="clear: both;"></p>
	<?php echo $prevUrlLink; ?>
<?php endif;?>
