<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$_product_id = $this->getProductId();
$_category_id = $this->getCategoryId();

$_product = Mage::getModel('catalog/product')->load($_product_id);;
$_category = Mage::getModel('catalog/category')->load($_category_id);;
?>

<!-- Tealium Send Friend javascript -->
<script type="text/javascript">
    var utag_data={
        site_region: "<?php echo Mage::app()->getLocale()->getLocaleCode(); ?>",
        site_currency: "<?php echo $store->getCurrentCurrencyCode(); ?>",
        page_name: "<?php echo htmlspecialchars($_product->getName(), ENT_QUOTES); ?>",
        page_type: "product send",
        product_id: "<?php echo $_product->getCourseId(); ?>",
        product_sku: "<?php echo $_product->getSku(); ?>",
        product_name: "<?php echo htmlspecialchars($_product->getName(), ENT_QUOTES); ?>",
        product_brand: "<?php echo $_product->getBrand(); ?>",
        product_category: "<?php echo $_category ? htmlspecialchars($_category->getName(), ENT_QUOTES) : 'no_category'; ?>",
        <?php if ($_product->getSpecialPrice()!='') echo 'product_unit_price: "'.number_format($_product->getSpecialPrice(),2) .'",'; ?>
        product_list_price: "<?php echo number_format($_product->getPrice(),2); ?>",
        user_id: Mage.Cookies.get('<?php echo Tgc_CookieNinja_Model_Ninja::COOKIE_USER_ID; ?>'),
        is_logged_in: Mage.Cookies.get('<?php echo Tgc_CookieNinja_Model_Ninja::COOKIE_LOGGED_IN; ?>')
    };
</script>