<?php
/**
 * Created by JetBrains PhpStorm.
 * User: aborria
 * Date: 13/02/14
 * Time: 15:01
 * To change this template use File | Settings | File Templates.
 */
?>

<div class="partner_page">
    <div class="partner_header">
        <img class="partner_header_image" src="<?php echo $this->getSkinUrl('images/partners/national-geographic/banner.png') ?>"/>
        <div class="logo_container"><img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/logo.png') ?>"/></div>
    </div>
    <div class="partner_content">
        <div class="partner_teaser_copy">
            <div class="ptc_description">
                <h2><?php echo $this->__('Partners is Learning');?></h2>
                <p><?php echo $this->__('Two trusted names in lifelong learning—The Great Courses and National Geographic—have joined forces to bring you exciting educational adventures. Join award-winning photographer Joel Sartore as he teaches you the secrets to taking great photographs in these two spectacular new courses. ');?></p>
            </div>
            <div class="ptc_image">
                <img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/devices.png') ?>"/>
            </div>
            <div class="mobile_teaser_copy">
                <div><a href="#"><?php echo $this->__('See more ways to learn photography with National Geographic');?>&#187;</a></div>
                <div class="teaser_copy_share">
                    <div class="body_social_networks">
                        <div class="body_social_text"><span><?php echo $this->__('Share:'); ?></span></div>
                        <div class="social_container">
                            <a href="#"><div class="social-button facebook"></div></a>
                            <a href="#"><div class="social-button twitter"></div></a>
                            <a href="#"><div class="social-button pinterest"></div></a>
                            <a href="#"><div class="social-button youtube"></div></a>
                            <a href="#"><div class="social-button email"></div></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>