<?php
/**
 * Boutique
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Boutique
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
/** $this Tgc_Boutique_Block_Left */
?>
<?php
$pages = $this->getPageCollection();

?>
<div class="boutique-page-leftnav">
    <div class="block">
        <div class="block_title">
            <strong>
                <span><?php echo $this->getBoutiqueName(); ?></span>
            </strong>
        </div>
        <ul class="left-navigation vert-navigation">
            <?php foreach ($pages as $page): ?>
                <li <?php if ($this->isCurrent($page)) : ?> class='active'  <?php endif;?> >
                    <a href="<?php echo $page['url']; ?>" title="<?php echo $page['title']; ?>">
                        <?php echo $page['title']; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <div id="mobile-layered-nav" class="mobile-layered-nav show-for-mobile">
            <select onchange="setLocation(this.value)">
                <?php foreach ($pages as $page): ?>
                    <option  <?php if ($this->isCurrent($page)) : ?> selected='selected'  <?php endif;?> value="<?php echo $page['url']; ?>">
                        <?php echo $page['title']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    (function($) {

        $(document).ready(function() {
            if ($(window).width() < 760) {
                var mobileCatMenu = $('.mobile-layered-nav');
                mobileCatMenu.find('select').coreUISelect();
            }
        });

    })(jQuery);
    //]]>
</script>