<?php $formId = $this->getFormId() ? $this->getFormId() : 'form-validate'; ?>
<label for="<?php echo $formId; ?>_telephone" class="required"><?php echo $this->__('Phone') ?><span class="optional">(optional)</span></label>
<div class="input-box">
    <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="<?php echo $formId; ?>_telephone" placeholder="<?php echo $this->__('###-###-####') ?>"/>
</div>