<?php
/**
 * BrightCove widget
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     DigitalLibrary
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
/** $this Tgc_DigitalLibrary_Block_BrightCoveMultimedia */

$userAgent = Mage::helper('Guidance_Useragent');
$deviceType = $userAgent->getDeviceType();
$osName = $userAgent->getOsName();

$width = 960;
$height = 270;
$playerId = '3594857503001';
$playerKey = 'AQ~~,AAABC2NgoKk~,lQq4tda2_S2Ams03cdE8vTVMW063OJmC';

if ($deviceType == 'tablet' || $deviceType == 'mobile') {
    $width = 768;
    $height = 300;
}

?>
<div id="brightCove-widget">
    <div id="brightCove-player">
        <script language="JavaScript" type="text/javascript" src="<?php echo $this::JS_LOCATION; ?>"></script>
        <object id="myExperience<?php echo $playerId; ?>" class="BrightcoveExperience">
            <param name="bgcolor" value="#ffffff" />
            <param name="width" value="<?php echo $width; ?>" />
            <param name="height" value="<?php echo $height; ?>" />
            <param name="playerID" value="<?php echo $playerId; ?>" />
            <param name="playerKey" value="<?php echo $playerKey; ?>" />
            <param name="isVid" value="0" />
            <param name="isUI" value="0" />
            <param name="dynamicStreaming" value="true" />
            <param name="@videoPlayer" value="<?php echo $this->getContentId(); ?>" />
            <!-- smart player api params -->
            <param name="templateLoadHandler" value="templateLoaded" />
            <param name="includeAPI" value="true" />
            <param name="wmode" value="transparent" />
        </object>


        <script language="JavaScript" type="text/javascript" src="http://admin.brightcove.com/js/BrightcoveExperiences.js"></script>
        <script type="text/javascript">brightcove.createExperiences();</script>
        <script type="text/JavaScript">
            var player, modExp, seekPoint, videoPlayer, APIModules, captionsModule, mediaEvent, iframePlayer;

            function templateLoaded(experienceID) {
                player = brightcove.api.getExperience(experienceID);
                modVP = player.getModule(brightcove.api.modules.APIModules.VIDEO_PLAYER);
                modExp = player.getModule(brightcove.api.modules.APIModules.EXPERIENCE);
                modCon = player.getModule(brightcove.api.modules.APIModules.CONTENT);
                modExp.addEventListener(brightcove.api.events.ExperienceEvent.TEMPLATE_READY, onTemplateReady);
            }
        </script>
    </div>
</div>