<?php
/**
 *
 */
?>
<?php
$customer = $this->getCustomer();
$subscriber = Mage::getModel('newsletter/subscriber')->loadByCustomer($customer);
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('Your Email and Notifications Preferences') ?></h1>
</div>
<?php echo $this->getChildHtml('form_before')?>
<div class="page-content subscription">
    <h3><?php echo $this->__('Notifications for') ?>: </h3>
    <strong class="name"><?php echo $this->escapeHtml($customer->getName()) ?></strong><br/>
    <strong class="mail"><?php echo $this->escapeHtml($customer->getEmail()) ?></strong>

    <?php echo $this->getChildHtml('notificationsPreferences') ?>

    <div class="clearfix"></div>
    <div class="divider"></div>
    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey') ?>
            <ul>
                <li class="control">
                    <?php if ($subscriber->isSubscribed()): ?>
                        <div style="padding-bottom:10px">
                            <?php echo $this->__('You are currently subscribed to marketing emails'); ?>
                        </div>
                    <?php else: ?>
                        <div style="padding-bottom:10px">
                            <?php echo $this->__('You are currently not subscribed to marketing emails'); ?>
                        </div>
                    <?php endif; ?>
                    <div class="input-box">
                        <input type="radio" name="is_subscribed" id="subscription" value="1"
                               <?php if ($subscriber->isSubscribed()): ?>checked<?php endif; ?> class="radio"/>
                        <label
                            for="subscription"><?php echo $this->__('I\'d like to receive all marketing emails (special offers, new course announcements, etc.) from The Great Courses') ?></label>
                    </div>
                    <div class="input-box">
                        <input type="radio" name="is_subscribed" id="unsubscription" value="0"
                               <?php if (!$subscriber->isSubscribed()): ?>checked<?php endif; ?> class="radio"/>
                        <label
                            for="unsubscription"><?php echo $this->__('Unsubscribe me from all marketing emails from The Great Courses') ?></label>
                    </div>
                </li>
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('customer.form.newsletter.extra') ?>
            </ul>
        </div>
        <div class="buttons-set form-buttons">
            <button type="submit" class="button" title="<?php echo $this->__('Save') ?>">
                <span><span><?php echo $this->__('Save') ?></span></span></button>
            <a class="cancel-btn button"
               href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Cancel') ?></a>
        </div>
    </form>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.newsletter.extra2') ?>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
(function ($) {
    $('.tool-tip-link').on('click', function (e) {
        e.preventDefault();
        $(this).next('.privacy-popup').show();
        $(this).parent().addClass('show');
    });

    var closeBtn = $('.privacy-popup .btn-remove');
    closeBtn.on('click', function (e) {
        e.preventDefault();
        $(this).parent('.privacy-popup').hide();
        $(this).parents().removeClass('show');
    });
})(jQuery);
//]]>
</script>
