<?php
/**
 * Customer verify account interstitial page
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Customer
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
/**
 * Customer verify account form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="account-login clearer">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-title">
        <h1><?php echo $this->__('Please Verify Account') ?></h1>
    </div>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra') ?>
    <form action="<?php echo $this->getUrl('customer/account/verifyPost'); ?>" method="post" id="verify-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="registered-users grid12-6">
            <div class="content">
                <h2><?php echo $this->__('Verify Account') ?></h2>

                <p><?php echo $this->__('Please log in to continue') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>

                        <div class="input-box">
                            <input type="text" name="login[username]"
                                   value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email"
                                   class="input-text required-entry validate-email"
                                   title="<?php echo $this->__('Email Address') ?>"/>
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><?php echo $this->__('Password') ?> <em>*</em></label>

                        <div class="input-box">
                            <input type="password" name="login[password]"
                                   class="input-text required-entry validate-tgc-password" id="pass"
                                   title="<?php echo $this->__('Password') ?>"/>
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <div class="buttons-set verify_buttons">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>"
                       class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" onclick="dataForm.submit()" class="button" title="<?php echo $this->__('Continue') ?>" name="send"
                            id="send2"><span><span><?php echo $this->__('Continue') ?></span></span></button>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('verify-form', true);
        Form.getElements('verify-form').each(function (element) {
            element.setAttribute('autocomplete', 'off');
        });
        //]]>
    </script>
</div>
