<div class="page-title">
    <h1><?php echo Mage::helper('enterprise_invitation')->__('Credit Application'); ?></h1>
</div>

<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<?php echo $this->getChildHtml('webforms')?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
