<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->__('Product Export - Manual Export') ?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="export_form" name="export_form" method="post" action="<?php echo Mage::helper('adminhtml')->getUrl('*/*/manualPost')?>">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>"/>
        <!--<input name="XDEBUG_PROFILE" type="hidden" value="1"/>-->
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product Export')?></h4>
        </div>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Profile')?> <span class="required">*</span></td>
                    <td class="input-ele">
                        <?php echo $this->getProfileSelectorHtml() ?> <a href="#" id="edit_profile_a">[Edit Profile]</a>
                    </td>
                </tr>
                <!--<tr>
                    <td class="label"><?php echo $this->__('Store Views')?></td>
                    <td class="input-ele">
                        <?php echo $this->getStoreViewSelectorHtml() ?>
                    </td>
                </tr>-->
                <tr>
                    <td class="label"><?php echo $this->__('Starting ID')?> <span class="required">*</span>
                    </td>
                    <td class="input-ele">
                        <input class="input-text required-entry" name="entity_from" id="entity_from" value="1"/> (1 = <?php echo $this->__('from the beginning')?>)
                    </td>
                </tr>
                <tr id="tr_last_id" style="display:none">
                    <td class="label">&nbsp;</td>
                    <td class="input-ele"><?php echo $this->__('Last <span id="last_entity"></span> id is <span id="last_id"></span> [<a href="#" onclick="$(\'entity_from\').value=$(\'last_id\').innerHTML; return false;">use</a>]')?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Ending ID')?> <span class="required">*</span></td>
                    <td class="input-ele">
                        <input class="input-text required-entry" name="entity_to" id="entity_to" value="0"/> (0 = <?php echo $this->__('until the last object created')?>)
                    </td>
                </tr>
                <tr>
                    <td class="label"><strong>Additional Filters</strong></td>
                    <td class="input-ele"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Date Range from')?></td>
                    <td class="input-ele"><?php echo $this->getCalendarHtml('daterange_from')?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Date Range to')?></td>
                    <td class="input-ele"><?php echo $this->getCalendarHtml('daterange_to')?></td>
                </tr>
                <!--<tr>
                    <td class="label"><?php echo $this->__('Export only not yet exported objects')?></td>
                    <td class="input-ele">
                        <input type="checkbox" name="filter_new_only" id="filter_new_only" style="margin-top:7px;"/>
                    </td>
                </tr>-->
                <tr>
                    <td class="label"><?php echo $this->__('Serve file to browser after exporting')?></td>
                    <td class="input-ele">
                        <input type="checkbox" name="start_download" id="start_download" style="margin-top:7px;"/>
                    </td>
                </tr>
                <tr>
                    <td class="label">&nbsp;</td>
                    <td class="input-ele">
                        <button class="scalable save" type="submit" id="export_button">
                        <?php if (Mage::getDesign()->getTheme('template') == 'go'): ?>
                            <span><span><span><?php echo $this->__('Export')?></span></span></span>
                        <?php else: ?>
                            <span><?php echo $this->__('Export')?></span>
                        <?php endif; ?>
                        </button>
                    </td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    <?php echo $this->getSelectValues() ?>
</script>
<script type="text/javascript">
    var selectedEntity = false;
    var inputFields = ['store_id', 'entity_from', 'entity_to', 'daterange_from', 'daterange_to', 'start_download', 'export_button'];
    Event.observe(window, 'load', function () {
    <?php
    if ($this->getRequest()->getParam('profile_id', false)) {
        ?>
        $('profile_id').value = '<?php echo htmlspecialchars($this->getRequest()->getParam('profile_id')) ?>';
        $$('select#profile_id option').each(function (o) {
            if (o.readAttribute('value') == $('profile_id').value) {
                o.selected = true;
                throw $break;
            }
        });
        <?php
    } else {
        ?>
        // If there is just one profile, select it by default
        if ($$('select#profile_id option').length <= 2) {
            $$('select#profile_id option').each(function (o) {
                if (o.readAttribute('value') !== '') {
                    o.selected = true;
                    throw $break;
                }
            });
        }
        <?php
    }
    ?>
        if ($('profile_id').value == '') {
            disableFields();
        } else {
            selectedEntity = $('profile_id').options[$('profile_id').selectedIndex].getAttribute('entity');
            updateStartingIdField();
            updatePredefinedSettings();
        }
        $('profile_id').onchange = function () {
            if (this.options[this.selectedIndex].value !== '') {
                selectedEntity = this.options[this.selectedIndex].getAttribute('entity');
                updateStartingIdField();
                enableFields();
                updatePredefinedSettings();
            } else {
                selectedEntity = false;
                disableFields();
            }
        }
    });
    function updatePredefinedSettings() {
        if (typeof $H(profile_settings.get($('profile_id').value)).get('export_filter_datefrom') !== 'undefined') {
            $('daterange_from').value = $H(profile_settings.get($('profile_id').value)).get('export_filter_datefrom');
        }
        if (typeof $H(profile_settings.get($('profile_id').value)).get('export_filter_dateto') !== 'undefined') {
            $('daterange_to').value = $H(profile_settings.get($('profile_id').value)).get('export_filter_dateto');
        }
        if (typeof $H(profile_settings.get($('profile_id').value)).get('start_download_manual_export') !== 'undefined') {
            if ($H(profile_settings.get($('profile_id').value)).get('start_download_manual_export') === "1") {
                $('start_download').checked = true;
            } else {
                $('start_download').checked = false;
            }
        }
        if (typeof $H(profile_settings.get($('profile_id').value)).get('export_filter_new_only') !== 'undefined') {
            if ($H(profile_settings.get($('profile_id').value)).get('export_filter_new_only') === "1") {
                $('filter_new_only').checked = true;
            } else {
                $('filter_new_only').checked = false;
            }
        }
        // Update profile links
        $('edit_profile_a').href = profile_edit_links.get($('profile_id').value);
    }
    function updateStartingIdField() {
        $('last_entity').innerHTML = selectedEntity;
        if (typeof last_entity_ids !== 'undefined') $('last_id').innerHTML = last_entity_ids.get(selectedEntity);
        $('tr_last_id').show();
    }
    function disableFields() {
        inputFields.forEach(function (element, index, array) {
            if ($(element)) {
                if (element != 'export_button') {
                    $(element).disable();
                }
            }
        });
    }
    function enableFields() {
        inputFields.forEach(function (element, index, array) {
            if ($(element)) {
                if (element != 'export_button') {
                    $(element).enable();
                }
            }
        });
    }
</script>
<!-- We are more important than other jquery versions/plugins on this page, so we load ours here. -->
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>xtento/productexport/jquery/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>xtento/productexport/jquery/jquery.fileDownload.js" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>xtento/productexport/jquery/jquery.blockUI.js" type="text/javascript"></script>
<script type="text/javascript">
    Mage.Cookies.clear('fileDownload');
    Mage.Cookies.clear('lastMessage');
    Mage.Cookies.clear('lastErrorMessage');
    Event.observe('export_form', 'submit', function (event) {
        Mage.Cookies.clear('fileDownload');
        Mage.Cookies.clear('lastMessage');
        Mage.Cookies.clear('lastErrorMessage');
        $('success-msg').hide();
        $('warning-msg').hide();
        jQuery.blockUI({
            message:jQuery('#export_dialog'),
            css:{
                border:'none',
                padding:'15px',
                backgroundColor:'#000',
                '-webkit-border-radius':'10px',
                '-moz-border-radius':'10px',
                opacity:.6,
                color:'#fff'
            }
        });
        jQuery('#close').click(function () {
            jQuery.unblockUI();
            return false;
        });
        jQuery.fileDownload(jQuery(this).attr('action'), {
            successCallback:function (url) {
                window.setTimeout(function () {
                    jQuery.unblockUI({
                        onUnblock:function () {
                            Mage.Cookies.clear('fileDownload');
                            $('messages').hide();
                            $('success-msg').show();
                            if (Mage.Cookies.get('lastMessage') != '') {
                                $('success-msg-text').innerHTML = Mage.Cookies.get('lastMessage').replace(/\+/g, ' ');
                                Mage.Cookies.clear('lastMessage');
                            } else {
                                $('success-msg-text').innerHTML = '<?php echo $this->__('Export completed successfully.')?>';
                            }
                            if (Mage.Cookies.get('lastErrorMessage') != '') {
                                $('warning-msg-text').innerHTML = Mage.Cookies.get('lastErrorMessage').replace(/\+/g, ' ');
                                $('warning-msg').show();
                                Mage.Cookies.clear('lastErrorMessage');
                            } else {
                                $('warning-msg').hide();
                            }
                        }
                    });
                }, 100);
                Event.stop(event);
            },
            failCallback:function (html, url) {
                //window.setTimeout(function(){
                //$('warning-msg-text').innerHTML = html;
                //jQuery.unblockUI();
                //$('warning-msg').show();
                //if (html != '') {
                //    $('warning-msg-text').innerHTML = html;
                //    Mage.Cookies.clear('lastMessage');
                //} else {
                //    $('warning-msg-text').innerHTML = '<?php echo $this->__('Export returned no response. Please check export execution log.')?>';
                //}
                //}, 250);
            },
            httpMethod:'POST',
            data:$(this).serialize()
        });
    });
</script>
<div id="export_dialog" style="display:none; cursor: default">
    <h2><?php echo Mage::helper('xtento_productexport')->__('Exporting... Please wait...')?></h2>
    <input type="button" id="close" value="Close Progress Window" style="padding:5px;"/>
</div>