<?php
/**
 *
 */
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
<div class="form-search">
    <label for="search"><?php echo $this->__('Search site:') ?></label><input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"/>&nbsp;<button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search for Courses') ?>');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');


        jQuery(function($){
            var keyupCounter = 0;
            $('#search').on('keyup', function(e) {
                var searchTitles = $('#search_autocomplete li:not(.autocomplete-title)');


                if($('#search_autocomplete').css('display') === 'block') {
                    if( e.which === 40 ) {
                        if( keyupCounter === searchTitles.length - 1 ) {
                            keyupCounter = -1;
                        }
                        keyupCounter++;
                        $('#search_autocomplete li').removeClass('selected');
                        $(searchTitles[keyupCounter]).addClass('selected');
                    } else if( e.which === 38 ) {
                        if( keyupCounter === 0 ) {
                            keyupCounter = searchTitles.length;
                        }
                        keyupCounter--;
                        $('#search_autocomplete li').removeClass('selected');
                        $(searchTitles[keyupCounter]).addClass('selected');

                    } else if(e.which === 13) {
                    	var autoCompleteListItemUrl = $(searchTitles[keyupCounter]).find('a').attr('href');
                    	window.location = autoCompleteListItemUrl;
                    }
                }
            })
        });

    //]]>
    </script>
</div>
</form>
