<?php $helpZoom = $this->helper('infortis_cloudzoom'); ?>
<?php if ($helpZoom->useLightbox()): ?>
	<?php
		$maxWidth	= $helpZoom->getCfg('lightbox/max_width');
		$maxHeight	= $helpZoom->getCfg('lightbox/max_height');
		$cfg = '';
		if ($maxWidth)
			$cfg .= ", maxWidth:'{$maxWidth}'";
		if ($maxHeight)
			$cfg .= ", maxHeight:'{$maxHeight}'";
	?>
	<script type="text/javascript">
        jQuery(document).ready(function(){

            jQuery(".lightbox-group").colorbox({
			<?php if ($helpZoom->getCfg('lightbox/group')): ?>
                rel:		'lightbox-group',
			<?php endif; ?>
                opacity:	0.5,
                speed:		300,
                current:	'<?php echo $this->__('image {current} of {total}') ?>'
				<?php if ($cfg) echo $cfg; ?>
			});

			<?php if ($helpZoom->getCfg('lightbox/group')): ?>
                jQuery(".cloud-zoom-gallery").removeClass("cboxElement");
                jQuery(".cloud-zoom-gallery").first().addClass("cboxElement");
			<?php endif; ?>

            jQuery(".cloud-zoom-gallery").click(function() {
                jQuery("#zoom-btn").attr('href', jQuery(this).attr('href'));
                jQuery("#zoom-btn").attr('title', jQuery(this).attr('title'));

				<?php if ($helpZoom->getCfg('lightbox/group')): ?>
                    jQuery(".cloud-zoom-gallery").each(function() {
                        jQuery(this).removeClass("cboxElement");
					});
                    jQuery(this).addClass("cboxElement");
				<?php endif; ?>

			});

        });
    </script>
<?php endif; ?>