<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/validate-zip-ca.js') ?>"></script>
<label for="shipping:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?></label>
<div class="input-box">
    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsshipping(false);" />
</div>
<script type="text/javascript">
//<!--
    document.observe('dom:loaded', function () {
        $('shipping:country_id').on('change', function (event) {
            if ('US' == event.element().getValue()) {
                $('shipping:postcode').addClassName('validate-zip');
                $('shipping:postcode').removeClassName('validate-ca');
                $('shipping:postcode').removeClassName('validate-zip-international');
            } else if ('CA' == event.element().getValue()) {
                $('shipping:postcode').removeClassName('validate-zip');
                $('shipping:postcode').removeClassName('validate-international');
                $('shipping:postcode').addClassName('validate-zip-ca');
            } else {
                $('shipping:postcode').removeClassName('validate-zip');
                $('shipping:postcode').removeClassName('validate-ca');
                $('shipping:postcode').addClassName('validate-zip-international');
            }
        });
    });
//-->
</script>
