<?php
/**
 *
 */
?>
<?php if($this->getProductData()->getId()): ?>
<div class="product-review">
    <div class="page-title">
        <h1><?php echo $this->__('Review Details') ?></h1>
    </div>
    <div class="product-img-box">
        <a class="product-image" href="<?php echo $this->getProductData()->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'image')->resize(285, 285); ?>" alt="<?php echo $this->escapeHtml($this->getProductData()->getName()) ?>" height="285" width="285" /></a>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
        <p><?php echo $this->__('Average Customer Rating:') ?></p>
        <?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
        <?php endif; ?>
    </div>
    <div class="details">
        <h2 class="product-name"><?php echo $this->escapeHtml($this->getProductData()->getName()) ?></h2>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
        <strong><?php echo ($this->isReviewOwner()) ? $this->__('Your Rating:') : $this->__('Rating:'); ?></strong>
        <table class="data-table review-summary-table">
        <?php foreach ($this->getRating() as $_rating): ?>
        <?php if($_rating->getPercent()): ?>
            <tr>
                <td class="label"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></td>
                <td class="value">
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                    </div></td>
            </tr>
        <?php endif; ?>
        <?php endforeach; ?>
        </table>
        <?php endif; ?>
        <p class="date">
            <?php if ($this->isReviewOwner()): ?>
                <?php echo $this->__('Your Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?>
            <?php else :?>
                <?php echo $this->__('Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?>
            <?php endif;?>
        </p>
        <p><?php echo nl2br($this->escapeHtml($this->getReviewData()->getDetail())) ?></p>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to My Reviews') ?></a></p>
    </div>
</div>
<?php endif; ?>
