<?php
/**
 * @var $this Infortis_UltraSlideshow_Block_Config
 */
?>
	<?php $cfg = $this->getSlideshowCfg(); ?>
    <script type="text/javascript">
    //<![CDATA[
		
		//jQuery(function($) {
		jQuery(window).load(function(){
			jQuery('.the-slideshow').flexslider({
				namespace:			"",
				animation:			<?php echo $cfg['fx']; ?>,
				
			<?php if ($cfg['easing']): ?>
				easing:				<?php echo $cfg['easing']; ?>,
				useCSS:				false,
			<?php endif; ?>
				
				animationLoop:		<?php echo $cfg['loop']; ?>,
				smoothHeight: true,
				
			<?php if ($cfg['timeout']): ?>
				slideshowSpeed:		<?php echo $cfg['timeout']; ?>,
			<?php else: ?>
				slideshow:			false,
			<?php endif; ?>
			
			<?php if ($cfg['speed']): ?>
				animationSpeed:		<?php echo $cfg['speed']; ?>,
			<?php endif; ?>
				
				pauseOnHover:		<?php echo $cfg['pause']; ?>
			});
		});
    //]]>
    </script>