<?php
/**
 * Created by JetBrains PhpStorm.
 * User: aborria
 * Date: 14/02/14
 * Time: 10:40
 * To change this template use File | Settings | File Templates.
 */
?>
<div class="partner_page">
    <div class="partner_content">
        <div class="partner_professors">
            <h2 class="partner_professor_title"><?php echo $this->__('Professor'); ?></h2>
            <ul>
                <li>
                    <div class="professor_info_cont">
                        <div class="professor_img ">
                            <img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/professor.png') ?>"/>
                        </div>
                        <div class="professor_info">
                            <div class="professor_name">
                                <span><?php echo $this->__('Joel Sartore'); ?></span>
                            </div>
                            <div class="professor_work">
                                <span><?php echo $this->__('National Geographic Magazine Fellow'); ?></span>
                            </div>
                            <div class="professor_desc">
                                <p><?php echo $this->__('Joel Sartore is a professional photographer and a regular contributor to National Geographic magazine. His assignments have taken him to some of the world&rsquo;s most beautiful and challenging environments and have brought him face to face with a diversity of wildlife in all 50 U. S. states and all seven continents. He was recently named a National Geographic Fellow for his work on "The Photo Ark," a multiyear project to document the world&rsquo;s biodiversity in studio portraits (see www.joelsartore.com and photoark.com). His photograph of a lion in a tree was voted the best picture by National Geographic magazine in 2011, and also won him a 2012 Veolia Environment award for wildlife photography.'); ?></p>
                                <p><?php echo $this->__('In addition to his work for National Geographic, Mr. Sartore has contributed to some of the most prestigious and widely read publications, including Audubon Magazine, Time, Life, Newsweek, and Sports Illustrated. Mr. Sartore and his work have been the subject of national broadcasts such as National Geographic Explorer, NBC Nightly News, NPR’s Weekend Edition, and an hour-long PBS documentary, At Close Range. He is also a regular contributor to CBS’s Sunday Morning with Charles Osgood.'); ?></p>
                                <p><?php echo $this->__('A noted author and public lecturer on photography to audiences around the world, Mr. Sartore has written several books that highlight his craft and his work. Among these are RARE: Portraits of America’s Endangered Species, Photographing Your Family, and Nebraska: Under a Big Red Sky.'); ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="professor_info_mobile">
                        <div class="professor_name">
                            <span><?php echo $this->__('Joel Sartore'); ?></span>
                        </div>
                        <div class="professor_work">
                            <span><?php echo $this->__('National Geographic Magazine Fellow'); ?></span>
                        </div>
                        <div class="mob_professor_medium_info">
                            <div class="professor_img ">
                                <img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/professor.png') ?>"/>
                            </div>
                            <div class="mob_professor_skills_share">
                                <div class="professor_skills_cont">
                                    <div class="professor_skill">
                                        <div class="prof_skill_image">
                                            <img  src="<?php echo $this->getSkinUrl('images/partners/national-geographic/institution_icon.png') ?>"/>
                                        </div>
                                        <span><?php echo $this->__('Professional Photographer');?></span>
                                    </div>
                                    <div class="professor_skill">
                                        <div class="prof_skill_image">
                                            <img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/podium_icon.png') ?>"/>
                                        </div>
                                        <span><?php echo $this->__('National Geographic Fellow');?></span>
                                    </div>
                                </div>
                                <div class="professor_share">
                                    <div class="body_social_networks">
                                        <div class="body_social_text"><span><?php echo $this->__('Connect With Professor:'); ?></span></div>
                                        <div class="social_container">
                                            <a href="#"><div class="social-button facebook"></div></a>
                                            <a href="#"><div class="social-button twitter"></div></a>
                                            <a href="#"><div class="social-button pinterest"></div></a>
                                            <a href="#"><div class="social-button youtube"></div></a>
                                            <a href="#"><div class="social-button email"></div></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="professor_desc">
                            <div class="prof_desc_container">
                                <p><?php echo $this->__('Joel Sartore is a professional photographer and a regular contributor to National Geographic magazine. His assignments have taken him to some of the world&rsquo;s most beautiful and challenging environments and have brought him face to face with a diversity of wildlife in all 50 U. S. states and all seven continents. He was recently named a National Geographic Fellow for his work on "The Photo Ark," a multiyear project to document the world&rsquo;s biodiversity in studio portraits (see www.joelsartore.com and photoark.com). His photograph of a lion in a tree was voted the best picture by National Geographic magazine in 2011, and also won him a 2012 Veolia Environment award for wildlife photography.'); ?></p>
                                <p><?php echo $this->__('In addition to his work for National Geographic, Mr. Sartore has contributed to some of the most prestigious and widely read publications, including Audubon Magazine, Time, Life, Newsweek, and Sports Illustrated. Mr. Sartore and his work have been the subject of national broadcasts such as National Geographic Explorer, NBC Nightly News, NPR’s Weekend Edition, and an hour-long PBS documentary, At Close Range. He is also a regular contributor to CBS’s Sunday Morning with Charles Osgood.'); ?></p>
                                <p><?php echo $this->__('A noted author and public lecturer on photography to audiences around the world, Mr. Sartore has written several books that highlight his craft and his work. Among these are RARE: Portraits of America’s Endangered Species, Photographing Your Family, and Nebraska: Under a Big Red Sky.'); ?></p>
                            </div>
                        </div>
                        <div class="prof_view_cont">
                            <div class="prof_view_more">
                                <div class="prof_view_more_img">
                                    <img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/view_more_down.png') ?>"/>
                                </div>
                                <span class="view_more_less_text"><?php echo $this->__('View More');?></span>
                            </div>
                            <div class="prof_view_less">
                                <div class="prof_view_more_img">
                                    <img src="<?php echo $this->getSkinUrl('images/partners/national-geographic/view_more_up.png') ?>"/>
                                </div>
                                <span class="view_more_less_text"><?php echo $this->__('View Less');?></span>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</div>