<?php
/**
 *The categories list on Home page
 */
?>
<div class="clearfix"></div>
<h3 class="section-title"><?php echo $this->__('Categories') ?></h3>
<div class="itemslider-wrapper itemslider-categories">

    <div class="itemslider itemslider-horizontal">
        <ul class="slides products-grid">
            <li class="category-slide">
                <a href="#">
                    <img src="<?php echo $this->getSkinUrl('images/tgc/category-better.jpg') ?>" alt="Better life"/>
                    <span class="category-name"><?php echo $this->__('Better Living') ?></span>
                </a>
            </li>
            <li class="category-slide">
                <a href="#">
                    <img src="<?php echo $this->getSkinUrl('images/tgc/category-better.jpg') ?>" alt="Better life"/>
                    <span class="category-name"><?php echo $this->__('Better Living') ?></span>
                </a>
            </li>
            <li class="category-slide">
                <a href="#">
                    <img src="<?php echo $this->getSkinUrl('images/tgc/category-better.jpg') ?>" alt="Better life"/>
                    <span class="category-name"><?php echo $this->__('Better Living') ?></span>
                </a>
            </li>
            <li class="category-slide">
                <a href="#">
                    <img src="<?php echo $this->getSkinUrl('images/tgc/category-better.jpg') ?>" alt="Better life"/>
                    <span class="category-name"><?php echo $this->__('Better Living') ?></span>
                </a>
            </li>
            <li class="category-slide">
                <a href="#">
                    <img src="<?php echo $this->getSkinUrl('images/tgc/category-better.jpg') ?>" alt="Better life"/>
                    <span class="category-name"><?php echo $this->__('Better Living') ?></span>
                </a>
            </li>
            <li class="category-slide">
                <a href="#">
                    <img src="<?php echo $this->getSkinUrl('images/tgc/category-better.jpg') ?>" alt="Better life"/>
                    <span class="category-name"><?php echo $this->__('Better Living') ?></span>
                </a>
            </li>
        </ul> <!-- end: slides -->
    </div> <!-- end: itemslider -->

</div> <!-- end: new-itemslider-wrapper -->
<script type="text/javascript">
//<![CDATA[
	jQuery(function($) {
		$('.itemslider-categories .itemslider').flexslider({
			namespace: "",
			animation: "slide",
            controlNav: false,
            animationLoop: false,
            itemWidth: 180,
            touch: true,
            scrollPerPage: true,
            slideshow: false,
            maxItems: 5,
            minItems: 1
        })
	});
//]]>
</script>