<?php
/**
 *The course notification on Home page
 */
?>

<div class="course-notification">
    <img class="course-img" src="<?php echo $this->getSkinUrl('images/tgc/course-notification.jpg') ?>" />
    <p><span class="course-label"><?php echo $this->__('You were watching:') ?></span><?php echo $this->__('Lecture 4 of 24: Perception, Perspective, and Punctuation from') ?> <strong><?php echo $this->__('Achieving Solutions for Life, Work, and Beyond') ?></strong>. <?php echo $this->__('Lorem ipsum line 3 if neccesary shows here') ?>.</p>
    <a class="button" rel="nofollow" href="#"><?php echo $this->__('Continue watching') ?></a>
    <a class="close-button" rel="nofollow" href="javascript:void(0)">X</a>
</div>