<?php
/**
 *
 */
?>
<?php
	$_productCollection = $this->getLoadedProductCollection();
?>
<?php //if ($_productCollection && ($_collectionSize = $_productCollection->count())): //Depre ?>
<?php if ($_productCollection && ($_collectionSize = $this->getCollectionCount())): ?>
<?php
	$_helper = $this->helper('catalog/output');
	$theme = $this->helper('ultimo');
	$helpLabels = $this->helper('ultimo/labels');
	$helpTemplate = $this->helper('ultimo/template');
	$helpImg = $this->helper('infortis/image');
	
	//Default image size
	$imgWidth = 168;
	$imgHeight = 168;
	
	//Aspect ratio settings
	if ($theme->getCfg('category/aspect_ratio'))
	{
		$imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio
	}
	
	//Block parameters
	$isResponsive = $this->getIsResponsive(); //is_responsive
	$breakpoints = $this->getBreakpoints(); //breakpoints
	$showItems = $this->getShowItems(); //show_products
	if (!$showItems)
	{
		$showItems = 5; //IMPORTANT: set default number of visible products
	}
	
	//Other block parameters:
	
		//Timeout (if set: automatic slideshow)
		$timeout = $this->getTimeout();
		if ($timeout == "null") //Special value: no automatic slideshow
		{
			$timeout = 0;
		}
		else
		{
			$timeout = intval($timeout);
			if (!$timeout) //Param not set or equals 0
			{
				$timeout = intval($theme->getCfg('product_slider/timeout'));
			}
		}
		
		//Initial delay
		$initDelay = intval($this->getInitDelay());
	
	//Additional CSS classes
	$sliderClasses = '';
	if($isResponsive)
	{
		$sliderClasses .= ' itemslider-responsive';
	}
	
    $r = $this->getFrontendHash();
?>

<h3 class="section-title padding-right"><?php echo $this->getBlockName(); ?></h3>
<div class="itemslider-wrapper">

	<div class="nav-wrapper gen-slider-arrows1 gen-slider-arrows1-pos-top-right" id="nav-wrapper-<?php echo $r; ?>"></div>
    
    <div class="itemslider itemslider-horizontal<?php if($sliderClasses) echo $sliderClasses; ?>" id="itemslider-<?php echo $r; ?>">
        <ul class="slides products-grid">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item">
                
                	<div class="product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">
                    
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
							<img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />

							<?php if ($theme->getCfg('category/alt_image')): ?>
								<?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
							<?php endif; ?>

							<?php echo $helpLabels->getLabels($_product); //Product labels ?>
						</a>
                    
                    	<?php //Add-to links
							if ($theme->getCfg('category_grid/display_addtolinks') != 0 
								&& $theme->getCfg('category_grid/addtolinks_simple'))
							{
								if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
								{
									echo $helpTemplate->getCategoryAddtoLinks(
									$_product, $this->getAddToCompareUrl($_product), 'addto-icons addto-onimage visible-onhover');
								}
								else //Always display
								{
									echo $helpTemplate->getCategoryAddtoLinks(
									$_product, $this->getAddToCompareUrl($_product), 'addto-icons addto-onimage');
								}
							}
						?>
                        
                    </div> <!-- end: product-image-wrapper -->

                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                    <?php if (Mage::helper('tgc_bv')->isBvEnabled()): ?>
                        <?php echo Mage::helper('bazaarvoice')->getInlineRatingForProduct($_product); ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                        
                        	<?php if ($this->getHideButton() == false): ?>
                            	<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php endif; ?>
                            
                        <?php else: ?>
                        
                        	<?php if ($this->getHideButton() == false): ?>
                            	<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            
                        <?php endif; ?>

                    	<?php //Add-to links
						if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))
						{
							if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
								echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons display-onhover');
							else //Always display
								echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons');
						}
						?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul> <!-- end: slides -->
    </div> <!-- end: itemslider -->

</div> <!-- end: itemslider-wrapper -->
<script type="text/javascript">
//<![CDATA[
	jQuery(function($) {
		
		$('#itemslider-<?php echo $r; ?>').flexslider({
			namespace: "",
			animation: "slide",
			easing: "easeInQuart",
			
			<?php if ($timeout): ?>
				slideshowSpeed: <?php echo $timeout; ?>,
				animationLoop: true,
			<?php else: ?>
				slideshow: false,
				animationLoop: false,
			<?php endif; ?>
			
			<?php if ($initDelay): ?>
				initDelay: <?php echo $initDelay; ?>,
			<?php endif; ?>
			
			<?php if ($speed = intval($theme->getCfg('product_slider/speed'))): ?>
				animationSpeed: <?php echo $speed; ?>,
			<?php endif; ?>
			
			pauseOnHover: true,
			controlNav: false,			
			controlsContainer: "#nav-wrapper-<?php echo $r; ?>",
			
			itemWidth: 188,
			<?php if ($showItems): ?>
				minItems: <?php echo $showItems; ?>,
				maxItems: <?php echo $showItems; ?>,
			<?php endif; ?>

			move: <?php echo intval($theme->getCfg('product_slider/move_items')); ?>
		})
		<?php if ($breakpoints): ?>
			.data("breakpoints", [ <?php echo $breakpoints; ?> ] )
		<?php elseif ($showItems): ?>
			.data("showItems", <?php echo $showItems; ?> )
		<?php endif; ?>
		; //IMPORTANT: don't remove semicolon!
		
	});
//]]>
</script>
<?php endif; ?>
