<div class="price-breaks">
	<p><?php echo $this->__('Lorem ipsum dolor sit amet') ?></p>
	<a class="cboxElement" href="#price-breaks-modal-data"><?php echo $this->__('Quantity Price Breaks') ?></a>
</div>

<script type="text/javascript">
    //<![CDATA[

    jQuery(document).ready(function(){
        jQuery(".price-breaks a").colorbox({inline:true, width:"75%"});
    });

    /*
    link for ajax data
    <a class="cboxElement" href="../content/ajax.html"><?php echo $this->__('Quantity Price Breaks') ?></a>
    */

    //]]>
</script>
