<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?php echo $this->__('Send Payments To:') ?></label>
            <p class="f-left"><?php echo $this->getMethod()->getPayableTo() ?></p>
        </li>
        <li>
            <a rel="nofollow" href="#" class="help-icon customer-po-what-is-this">?</a>
            <label for="payment:customer_po" ><?php echo $this->__('Customer PO:') ?></label>
            <div class="input-box">
                <input type="text" id="payment:customer_po" name="payment[customer_po]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text" value="" />
            </div>
        </li>
        <?php endif; ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
            <address class="checkmo-mailing-address">
                <?php echo nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
            </address>
        </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
