<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li class="title">
        <h4><?php echo $this->__('Customer Purchase Order')?></h4>
    </li>
    <li>
        <p><?php echo $this->__('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a nulla vel leo laoreet fringilla laoreet sed justo. Pellentesque nec nulla est. Cras ac lorem enim. Donec augue mauris, ac')?></p>
    </li>
    <li>
        <label for="po_number" class="required"><em>*</em><?php echo $this->__('Purchase Order #') ?></label>
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase Order Number') ?>" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getInfoData('po_number')) ?>" />
        </div>
    </li>
</ul>
