<?php
/**
 * Digital Library Account
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     DigitalLibrary
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
/** $this Mage_Core_Block_Template */
?>
<?php echo $this->getChildHtml('stream-faq-block'); ?>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#nav-stream-faqs').addClass('active');
    });
</script>
