<?php
/**
 * Digital Library Account
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Professor Bio Page Template
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
?>

<div class="professor-bio-page">

    <?php echo $this->getChildHtml('professor_data')?>
    <?php echo $this->getChildHtml('professor_sub_data')?>

</div>