<?php
/**
 * Digital Library Account
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    Tgc
 * @package     Professor Data Template
 * @copyright   Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */
/* @var $this Tgc_Professors_Block_Professor */
?>
<?php
    /* @var $professor Tgc_Professors_Model_Professor */
	$professor = $this->getParentBlock()->getProfessor();
    $profAlmamaters = $professor->getAlmaMaters();
?>
<h3 class="section-title">
    <?php echo $this->__('Professor %s %s', $this->escapeHtml($professor->getFirstName()), $this->escapeHtml($professor->getLastName())) ;?>
</h3>

<div class="container-with-shadow">
    <div class="professor-data-container clearfix">
        <div class="left-part">
            <div class="professor-photo-block">
                <img src="<?php echo $professor->getPhoto();?>" alt="<?php echo $this->__('Professor %s %s', $this->escapeHtml($professor->getFirstName()), $this->escapeHtml($professor->getLastName())) ;?>">
            </div>
            <div class="professor-work-data">
                <div class="work-places-block">
                    <ul>
                        <?php foreach ($professor->getTeachingAt() as $value) : ?>
                            <li class="college">
                                <div>
                                    <?php echo $this->escapeHtml($value->getName()) ?>
                                </div>
                            </li>
                        <?php endforeach?>

                        <?php foreach ($profAlmamaters as $value) : ?>
                            <li class="university">
                                <div>
                                    <?php echo $this->escapeHtml($value->getName()) ?>
                                </div>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>

                <?php if($professor->hasContactInfo()) : ?>
                    <div class="block-for-social-buttons">
                        <div class="text-block">Connect with Professor:</div>
                        <div class="buttons-list">
                            <?php if($professor->getFacebook() != '') : ?>
                                <a target="_blank" href="<?php echo $professor->getFacebook()?>" class="social-button facebook"></a>
                            <?php endif ?>
                            <?php if($professor->getTwitter() != '') : ?>
                                <a target="_blank" href="<?php echo $professor->getTwitter()?>" class="social-button twitter"></a>
                            <?php endif ?>
                            <?php if($professor->getPinterest() != '') : ?>
                                <a target="_blank" href="<?php echo $professor->getPinterest()?>" class="social-button pinterest"></a>
                            <?php endif ?>
                            <?php if($professor->getYoutube() != '') : ?>
                                <a target="_blank" href="<?php echo $professor->getYoutube()?>" class="social-button youtube"></a>
                            <?php endif ?>
                            <?php if($professor->getEmail() != '') : ?>
                                <a target="_blank" href="<?php echo $professor->getEmail()?>" class="social-button email"></a>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endif;?>

            </div>
        </div>
        <div class="right-part">
            <div class="professor-bio">
                <div class="divider"></div>
                <q>
                    <?php echo $professor->getQuote();?>
                </q>
                <div class="divider"></div>
                <div class="professor-bio-info">
                    <?php echo $professor->getBio();?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix">
    <?php /*
    <div class="block-for-social-buttons">
        <div class="text-block">Share:</div>
        <div class="buttons-list">
            <a href="#" class="social-button facebook"></a>
            <a href="#" class="social-button twitter"></a>
            <a href="#" class="social-button pinterest"></a>
            <a href="#" class="social-button youtube"></a>
            <a href="#" class="social-button email"></a>
        </div>
    </div>
    */ ?>
</div>

