<?php if(Mage::getStoreConfig("bazaarvoice/general/enable_bv") === "1"): ?>
<?php
$doShowContentJs = Mage::getStoreConfig('bazaarvoice/qa/do_show_content_js');
?>
<?php if(Mage::getStoreConfig("bazaarvoice/qa/enable_qa") === "1"): ?>
<div id="BVQAContainer"></div>
<script type="text/javascript">
    $BV.ui( 'qa', 'show_questions', {
        subjectType: "product",
        doShowContent : function () {
            <?php echo $doShowContentJs ?>
        }
    });
</script>
<?php endif; ?>
<?php endif; ?>
