<?php
/**
 * Created by JetBrains PhpStorm.
 * User: aborria
 * Date: 2/5/14
 * Time: 3:20 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<div class="body_social_networks">
    <div class="body_social_text"><span><?php echo $this->__('Share:'); ?></span></div>
    <div class="social_container">
<!--    <div class="social_container float_left">-->
        <a href="#"><div class="social-button facebook"></div></a>
        <a href="#"><div class="social-button twitter"></div></a>
        <a href="#"><div class="social-button pinterest"></div></a>
        <a href="#"><div class="social-button youtube"></div></a>
    </div>
    <div class="clearfix"></div>
</div>