<?php
/**
 * Customer password
 */
?>
<div class="col2-set customer-password">
    <div class="row">
        <div class="info-box">
            <h6 class="box-title">
                <div class="col-data-wrapper">
                    <span class="col-label"><?php echo $this->__('Password') ?></span>
                </div>
                <span class="col-content"></span><span class="col-action">
                    <a class="button secondary-btn" rel="nofollow" href="#"><?php echo $this->__('Edit') ?></a>
                </span>
            </h6>

            <div class="box-content centered">
                <div class="loader" style="display: none;">
                    <div class="hover"></div>
                    <div class="msg"><?php echo $this->__('Processing...'); ?></div>
                </div>
                <div class="notice-container" style="display: none;">
                    <div class="hover"></div>
                    <div class="msg"></div>
                </div>
                <form action="#" method="post" autocomplete="off" id="form-password">
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="current_password"><?php echo $this->__('Current') ?></label>

                                <div class="input-box">
                                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                                    <input type="text" class="input-text no-display" name="dummy" id="dummy"/>
                                    <input type="password" class="input-text required-entry" name="current_password"
                                           id="current_password"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="password"><?php echo $this->__('New') ?></label>

                                <div class="input-box">
                                    <input type="password"
                                           class="input-text required-entry validate-both-passwords validate-tgc-password"
                                           name="password" id="password" placeholder="Password"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="confirmation"><?php echo $this->__('Confirm') ?></label>

                                <div class="input-box">
                                    <input type="password" class="input-text required-entry validate-both-passwords"
                                           name="confirmation" id="confirmation" placeholder="Confirm Password"/>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <div class="buttons-set form-buttons">
                        <button type="submit" class="button" title="<?php echo $this->__('Save') ?>">
                            <span><span><?php echo $this->__('Save') ?></span></span></button>
                        <a class="cancel-btn button" rel="nofollow" href="#">Cancel</a>
                    </div>
                </form>
                <script type="text/javascript">
                    //<![CDATA[
                    var passwordForm = new customerDashboardForm({
                        form:                          $('form-password'),
                        formSubmitUrl:                 '<?php echo $this->getUrl('tgc_customer/dashboard/savePassword'); ?>',
                        formContainer:                 $('form-password').up('div'),
                        autoHideFormContainerDelay:    3000,
                        onFormSubmitSuccessCallback:   function () {$('form-password').select('input').each(function (el) {el.setValue('');});},
                        onFormContainerHideCallback:   function () {$('form-password').up('div.info-box').down('.box-title .col-action .button').removeClassName('disabled');$('form-password').up('div.info-box').removeClassName('show');},
                        loaderHoverContainer:          $('form-password').up('div').down('.loader'),
                        resultNoticeContainer:         $('form-password').up('div').down('.notice-container'),
                        resultNoticeMessagesContainer: $('form-password').up('div').down('.notice-container .msg'),
                        autoHideSuccessNoticeDelay:    3000,
                        autoHideErrorNoticeDelay:      3000,
                        successMsgPrefix:              '<span class="success-prefix"><?php echo $this->__('Success!')?></span> ',
                        errorMsgPrefix:                '<span class="error-prefix"><?php echo $this->__('Error!')?></span> '
                    });

                    $('form-password').down('.cancel-btn').observe('click', function (event) {
                        Event.stop(event);
                        var form = $('form-password');
                        form.up('div').hide();
                        form.up('div.info-box').down('.box-title .col-action .button').removeClassName('disabled');
                        form.up('div.info-box').removeClassName('show');
                    });
                    //]]>
                </script>
            </div>
        </div>
    </div>
</div>

