<?php
/**
 * @category    Mana
 * @package     Mana_Core
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
?>
<div id="m-wait" style="display:none;" class="custom_loader">
    <div class="custom_loader_cont">
        <div class="loader_background"></div>
        <p class="loader" id="loading_mask_loader">
            <span class="loader_img_cont"><img src="<?php echo $this->getSkinUrl('images/loader-gif.gif') ?>" alt="<?php echo $this->__('Processing...') ?>"/></span>
            <span><?php echo $this->__('Processing...') ?></span>
        </p>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.custom_loader .custom_loader_cont').css({'marginLeft' : jQuery('.main-container').width() - jQuery('.col-main').outerWidth(true)});
        jQuery('.custom_loader .custom_loader_cont').width((jQuery('.col-main').width() * 80) / 100);
    });
    jQuery(window).resize(function() {
        jQuery('.custom_loader .custom_loader_cont').css({'marginLeft' : jQuery('.main-container').width() - jQuery('.col-main').outerWidth(true)});
        jQuery('.custom_loader .custom_loader_cont').width((jQuery('.col-main').width() * 80) / 100);
    });
</script>