<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/validate-zip-au.js') ?>"></script>
<label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?></label>
<div class="input-box">
<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>"
       name="billing[postcode]" id="billing:postcode"
       value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
       class="input-text validate-zip-international validate-zip-au <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"/>
</div>
